### ISSUE TITLE
MediaPipe

### ISSUE THREAD

**Issue by Zekhire** [TaatiTeam/MotionAGFormer#11]
Hello.

Is this possible to train the MotionAGFormer model on the MediaPipe skeleton? Or any other skeleton with the feet?

**Comment by SoroushMehraban** [comment]
Hello,
Yes it is possible. But you have to take two things into account:
1. Spatial GCNFormer's adjacency matrix relies on physically connected edges. [Here](https://github.com/TaatiTeam/MotionAGFormer/blob/master/model/modules/graph.py#L6) on line 6 I defined `CONNECTIONS` that connects human joints based on Human3.6M format. You have to modify it for the new format.
2. In case your new skeleton format has more (or less) than 17 joints, you have to go to the [model definition here](https://github.com/TaatiTeam/MotionAGFormer/blob/master/model/MotionAGFormer.py) and change everywhere in code that I hardcoded 17 as the number of joints.
