### ISSUE TITLE
About the required GPU memory during training

### ISSUE THREAD

**Issue by sk-zhang** [TaatiTeam/MotionAGFormer#14]
Hello, this is indeed an excellent piece of work. I'd like to ask, approximately how much GPU memory is needed to train the Base model as described in the paper?

**Comment by SoroushMehraban** [comment]
Thanks @sk-zhang 
We used 2x A40 GPUs. So a total of 80GB memory with batch size of 16. This was used for all the variants and it didn't necessarily used all the GPU memory. Like the Base variant used only 53% of the GPU memories (40GB) by using batch size of 16 during training.

**Comment by sk-zhang** [comment]
I see. Thank you.
