### ISSUE TITLE
"Quota exceeded error" while downloading the model

### ISSUE THREAD

**Issue by a-kungwani** [TaatiTeam/MotionAGFormer#17]
Dear Team,

I appreciate your work and a detailed documentation.

I'm unable to download the pre-trained weights of S and XS H36M model from the drive link due to "quota exceeded error". I request you to help me if any other link is available to download the models.

Best Regards
Aman

**Comment by SoroushMehraban** [comment]
Hi @a-kungwani,
Just checked the links and it works properly on my side. Are you sure the problem is not from your side?

**Comment by a-kungwani** [comment]
Hi @SoroushMehraban, Thank you for your reply

I Just tried with my personal PC and it is getting downloaded. Before I was trying with my Lab PC and I think might be some problem there.

Sorry for the disturbance and Thank you once again for the verification!

Best Regards,
Aman
