### ISSUE TITLE
Input 2D augmentation

### ISSUE THREAD

**Issue by a-kungwani** [TaatiTeam/MotionAGFormer#18]
Hello @SoroushMehraban, Hope you are doing well!

In demo/vis.py, you have been using input_2D_aug which has been flipped(*-1) in the x coordinates if I am not wrong. Further rearranging has been done using left and right joints to my knowledge. But while prediction i.e. output_3D_flip and non flipped only input 2D has been used and no where the augmentated keypoints array has been used. I request you to help me to understand this well. (line 240-249)

Thanking You

Best Regards
Aman

**Comment by SoroushMehraban** [comment]
Good catch @a-kungwani. 
Fixed it.
