### ISSUE TITLE
Train/Test for multiple people in the scene

### ISSUE THREAD

**Issue by jagdishbhanushali** [TaatiTeam/MotionAGFormer#19]
Thank you for amazing work. I have tested inference and it worked out of the box great. 
However I want to test this on in-the-wild videos where there are multiple people in the scene. After looking at the code I see you are always assuming there is only one person in the scene.

How to run inference as well as train for multiple person in the same frame? Do I have to separate each person's 2d pose based on tracking and then do the inference?

Thanks,
Jagdish Bhanushali

**Comment by SoroushMehraban** [comment]
Thanks, @jagdishbhanushali.
That's true when we have multiple people you have to do person detection/tracking first, crop the region containing a single person and then give it to the model.
