### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by faisalshahbaz** [TaatiTeam/MotionAGFormer#2]
Dear Team,

I trust this message finds you well. I am currently facing an issue and would appreciate your assistance in resolving it. Could you please provide guidance on the matter?

```
Generating 2D pose...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 328, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 90, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "MotionAGFormer/demo/lib/hrnet/gen_kpts.py", line 169, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array
```

**Comment by SoroushMehraban** [comment]
Hi Faisal,
Are you using a custom video provided by yourself as input? If so, could you please share the video with me via email for debugging purposes? My email address is [soroush.mehraban@mail.utoronto.ca](mailto:soroush.mehraban@mail.utoronto.ca).

**Comment by SoroushMehraban** [comment]
Since no response is received from you, I close this issue for now.

**Comment by claragarciamoll** [comment]
First of all, thanks for you amaizing work.
I have the same problem using the video sample_video.mp4 that you propose for the demo.

Traceback (most recent call last):
  File "demo/vis.py", line 328, in <module>
    get_pose2D(video_path, output_dir)
  File "demo/vis.py", line 90, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "MotionAGFormer\demo\lib\hrnet\gen_kpts.py", line 166, in gen_video_kpts
    keypoints = keypoints.transpose(1, 0, 2, 3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array

Could you check this?

**Comment by SoroushMehraban** [comment]
Hi @claragarciamoll 
Could you send me the video via email so that I can work on it?
@soroush.mehraban@mail.utoronto.ca

**Comment by jagdishbhanushali** [comment]
I also got the same error.
I got it solved by just passing sample_video.mp4 as argument for --video. By default in the code it always concatenate you argument with './demo/video/' path.

You might also get exception in line 196
`  
File "demo/vis.py", line 196, in get_pose3D
    model_path = sorted(glob.glob(os.path.join('checkpoint', 'motionagformer-b-h36m.pth.tr')))[0]
IndexError: list index out of range
`
Update line 196 with following.
`model_path = sorted(glob.glob(os.path.join('./demo/lib/checkpoint', 'motionagformer-b-h36m.pth.tr')))[0]`

**Comment by jagdishbhanushali** [comment]
I got same error even on other video format, even though video file is present in correct directory. While debugging I found out that cv doesn't able to load video properly. It is even unable to identify crrect number of frames. 

Removing  concatanation part at line 324 helped. So now you'll pass complete path of video and it works 
`video_path = args.video`
