### ISSUE TITLE
how to add gaussian noise?

### ISSUE THREAD

**Issue by SJM0018** [TaatiTeam/MotionAGFormer#21]
That is a great work! Now I want to study the robustness to noise of the model. I need to add some Gaussian noise to the ground truth of the 2D joint points on Human3.6M. How should I do this? THANK YOU！！！
<img width="852" alt="image" src="https://github.com/TaatiTeam/MotionAGFormer/assets/101796109/921dc4d3-07b6-4c0f-9c7e-63c0e7a1706a">
It might be appropriate to add code in this function in motion_dataset.py？

**Comment by SoroushMehraban** [comment]
Thanks @SJM0018 
MotionBERT (That we used their code and modified it) already have done it. You can check it from their repository [here](https://github.com/Walter0807/MotionBERT/blob/main/lib/data/augmentation.py#L29)
