### ISSUE TITLE
About base model

### ISSUE THREAD

**Issue by yumianhuli1** [TaatiTeam/MotionAGFormer#22]
Hello! Dear TaatiTeam！
May I ask which data-sets are used to train the default base model checkpoint- Motionagex-B-H36M.pth?

**Comment by SoroushMehraban** [comment]
Hi @yumianhuli1 
As the name suggests, Human3.6M (H36M) is used for training.

**Comment by yumianhuli1** [comment]
> Hi @yumianhuli1 As the name suggests, Human3.6M (H36M) is used for training.

thanks
