### ISSUE TITLE
The proposed environment

### ISSUE THREAD

**Issue by yumianhuli1** [TaatiTeam/MotionAGFormer#23]
Hello! Dear TaatiTeam！

I ran python demo/vis.py --video sample_video.mp4, but in Generating 2D pose...

100% | █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ | 207/207 [00:11 "00:00, 17.56 it/s]

Generating 2D pose image...

100% | █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ | 207/207 [00:03 "00:00, 52.58 it/s]

When running Generating 3D pose... When an error is reported:

Traceback (most recent call last):

File "demo/vis.py", line 333, in <module>

get_pose3D(video_path, output_dir)

File "demo/vis.py", line 252, in get_pose3D

output_3D_flip = flip_data(model(input_2D_aug))

File "demo/vis.py", line 182, in flip_data

flipped_data = copy.deepcopy(data)

File "C:\Users\win11\anaconda3\envs\MagicCap\lib\copy.py", line 153, in deepcopy

y = copier(memo)

File "C:\Users\win11\anaconda3\envs\MagicCap\lib\site-packages\torch\_tensor.py", line 86, in __deepcopy__

raise RuntimeError(

RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

The proposed environment for this project is:

Python 3.8.10

PyTorch 2.0.0

CUDA 12.2

But in fact, there is no such combination, so I tried to install on the conda environment:

The torch - 2.0.0 + cu117 - cp38

The torch - 2.0.0 + cu118 - cp38

The torch - 2.1.0 + cu121 - cp38

These three combinations, but are reported Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment such an error.

**Comment by arjunvdatta** [comment]
Faced the same exact issue

**Comment by ShadowDawg** [comment]
I'm facing the exact same issue on windows. I know its unlikely but could it have something to do with running it on windows rather than on linux?

**Comment by SoroushMehraban** [comment]
@yumianhuli1, @ShadowDawg 
Thanks for bringing up the issue. Just fixed it.

**Comment by ShadowDawg** [comment]
@SoroushMehraban Thanks for your quick response. I cloned the latest repo and tried to run the demo again but now the following error is being thrown:
```
Traceback (most recent call last):
  File "demo/vis.py", line 188, in <module>
    def get_pose3D(video_path, output_dir):
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by SoroushMehraban** [comment]
@ShadowDawg That's strange. could you replace `@torch.no_grad` with `@torch.no_grad()` on line 187? I think I missed the parenthesis.

**Comment by ShadowDawg** [comment]
@SoroushMehraban adding the parenthesis did the trick, it works fine now! Thanks for your quick help!
