### ISSUE TITLE
Question about Training Dataset

### ISSUE THREAD

**Issue by Millba** [TaatiTeam/MotionAGFormer#3]
Thank you for the excellent project. I am interested in using this model for a project and am curious about which joint points were used for training from the Human3.6M and MPI-INF-3DHP datasets, respectively.

**Comment by SoroushMehraban** [comment]
In the constant file located at https://github.com/TaatiTeam/MotionAGFormer/blob/master/data/const.py, you'll find joint names defined. The first dictionary establishes a connection between each joint number and its corresponding label in Human3.6M, while the second dictionary links each joint in Human3.6M to the MPI-INF-3DHP format. For instance, Human3.6M's joint 0 or MPI-INF-3DHP's joint 14 aligns with the sacrum (bottom torso).

You can also view the visualization of Human3.6M in figure below:
![Human3.6M Keypoint naming](https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00530-022-00980-0/MediaObjects/530_2022_980_Fig8_HTML.png?as=webp)
Image is from [this paper](https://link.springer.com/article/10.1007/s00530-022-00980-0)

**Comment by Millba** [comment]
Ah! It was information included in the file. Thank you for your kind response!
