### ISSUE TITLE
what if we combine MotionBert and MotionAGFormer together?

### ISSUE THREAD

**Issue by diamondcm** [TaatiTeam/MotionAGFormer#33]
anyone tried?

**Comment by SoroushMehraban** [comment]
@diamondcm 
I think architecture-wise if we add temporal-spatial transformer branch to the MotionAGFormer (or even temporal-spatial GCNFormer), the computational complexity will be huge. The model is already expensive to train and by adding more branches I assume it adds many parameters that we don't have enough data for it. But you can reduce the number of channels or divide the channels by four and pass C/4 to each branch and then concatenate instead. You're welcome to try!

**Comment by diamondcm** [comment]
@SoroushMehraban 
definitely will! For lower loss maybe:)
Thanks.

**Comment by diamondcm** [comment]
@SoroushMehraban 
Hi again!
Is there global model in AGFormer? I noticed one of motionbert model is global with output that is not aligned with root.
Thanks.

**Comment by SoroushMehraban** [comment]
@diamondcm 
Can you give me a link to the code you're referring to in MotionBERT?

**Comment by diamondcm** [comment]
https://github.com/Walter0807/MotionBERT/blob/main/docs/inference.md

@SoroushMehraban 
Hi, here you can check the gif of demo is global position.
and the picture I posted is the list of models it contains. The demo uses MB_ft_h36m_global_lite. And the output is global position of joints directly.

![image](https://github.com/TaatiTeam/MotionAGFormer/assets/4925749/9aa3d7fe-3eb4-4f0e-8bec-8d4d8355a3b2)

**Comment by SoroushMehraban** [comment]
@diamondcm 
You can do the same thing by placing 'root_rel' to 'False' on config file of MotionAGFormer when training the model. I haven't done it but probably should have done it for demo.

**Comment by diamondcm** [comment]
@SoroushMehraban 
Got it! Thanks.

BTW, do you plan to test global result and replace your demo with global result, coz it may look more similar to realistic with hip moving:)

**Comment by SoroushMehraban** [comment]
@diamondcm 
I have lots of experiments to perform these days for other projects. I don't think I can make it soon.

**Comment by diamondcm** [comment]
ok, good luck.
Thanks for reply:)

**Comment by temi-20** [comment]
Hi @diamondcm, did you train a global model on H3.6M? If yes, could you share it? Thanks in advance!
