### ISSUE TITLE
Input frame length for MPI-INF-3DHP dataset

### ISSUE THREAD

**Issue by hehulingxiao** [TaatiTeam/MotionAGFormer#34]
Many thanks for the great work!

I wonder why the input frame length is chosen as 81 instead of 243 for MPI-INF-3DHP dataset. Have you tried training on 243 frames and how is the performance? Thank you!

**Comment by SoroushMehraban** [comment]
@StevenSmith2000 
No we haven't. We followed previous approaches and for a fair comparison used 81 instead. They mainly say in the paper that's because the original video lengths are not as long as Human3.6M.
