### ISSUE TITLE
lamdas of loss have ever changed or adjust with training?

### ISSUE THREAD

**Issue by diamondcm** [TaatiTeam/MotionAGFormer#37]
# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

Hi again, My result got a little bit jitter, comparing to yours. 
So those lambdas stay the same in your training?

**Comment by SoroushMehraban** [comment]
@diamondcm 
Yes, we didn't play with these loss coefficients and it's the same as what MotionBERT used.
