### ISSUE TITLE
What is the“sequence with confidence score”?

### ISSUE THREAD

**Issue by Lxg-233** [TaatiTeam/MotionAGFormer#38]
----Hi,thank you for your code!
----- I want konw what is the “sequence with confidence score”. When I debug the code,I find our input x is TJ3. really thank you for your opensource！

**Comment by SoroushMehraban** [comment]
Hello @libksion,
When you run 2D pose detector on an image, in addition to (x, y) it also gives you how confident it is for that estimation. So confidence score is a value in range [0, 1] that model also receives as input. At inference time if you don't have that value, you can use score 1, meaning that you're 100% sure the keypoint is located at that point (if it isn't the result is expected to be a bit worse).
