### ISSUE TITLE
2D pose detector used in the model

### ISSUE THREAD

**Issue by a-kungwani** [TaatiTeam/MotionAGFormer#40]
Hi @SoroushMehraban, Hope you are doing well!

I wanted to ask you regarding the 2D keypoint detector used in model. I need some documentation and literature for my work. Do you have any reference or link for the 2D detector?

Thank you in advance

Best Regards
Aman

**Comment by SoroushMehraban** [comment]
Hi @a-kungwani,
The same 2D keypoint detector that MotionBERT tried is used in this project. It's [Stacked Hourglass](https://arxiv.org/pdf/1603.06937). Note that the other difference between MotionAGFormer and MotionBERT compared to other models is that they use only (x, y) but here we use (x, y, confidence_score).

**Comment by a-kungwani** [comment]
@SoroushMehraban Thank you for your kind reply!
