### ISSUE TITLE
About the inputs to the modules

### ISSUE THREAD

**Issue by 2819982540** [TaatiTeam/MotionAGFormer#47]
The paper describes that the input to the Temporal MetaFormer is the pose sequence frames, but the diagram of the paper shows that the input to the Temporal MetaFormer is the output of the Spatial MetaFormer, which puzzles me. May I ask what are the inputs to the spatial MetaFormer and temporal MetaFormer respectively? Thanks!

**Comment by SoroushMehraban** [comment]
@2819982540 Originally we have a tensor with shape BxTxJx3 where:
- B: batch size
- T: Number of frames
- J: number of joints
- 3: (x, y, confidence_score)

The model first uses a linear layer that maps the 3 to a D dimension vector. So as the input we have BxTxJxD. Then Spatial MetaFormers receive (BT)xJxD as the input. Meaning that:
- We have J tokens
- Each token is D dimension
- We have BT as the batch of data

Then after calculating the output. The output of spatial metaformers are reshaped to (BJ)xTxD. Meaning that:
- We have T tokens (frames)
- Each token is D dimension
- We have BJ as the batch size

Hope it helps!
