### ISSUE TITLE
How to get 2D ground truth data for training? Help!

### ISSUE THREAD

**Issue by SongrainZhou** [TaatiTeam/MotionAGFormer#5]
Thank you for the excellent project and I am very interested in your project. I want to train with 2D ground truth keypoints. Could you please tell me how to get 2D ground truth data for training?

**Comment by SoroushMehraban** [comment]
You can do it by setting `use_proj_as_2d` to be True in config file. By setting it, it doesn't use the 2D input and use 2D projection (with confidence score of 1) as the 2D input.

**Comment by SongrainZhou** [comment]
Thank you for your answer!!!
