### ISSUE TITLE
About 3DHP

### ISSUE THREAD

**Issue by Arginonn** [TaatiTeam/MotionAGFormer#50]
Hello author, thank you very much for sharing. This is an excellent piece of work. When running train_3dhp.py, I found that the dimension of input x in line 50 of the code is [N, T, 17,3]. My understanding is that the in_channel here should not be 2, should we use 2D pose as input? In reality, the 3D pose is used as input. This is where I don't quite understand. Or rather, I misunderstood. Finally, thank you for your answer!  : )
![1](https://github.com/user-attachments/assets/a061becd-0e58-4ac2-8884-8d163d2d48c3)
![2](https://github.com/user-attachments/assets/090852d0-7b8d-4890-8041-37ceccc5eea9)

**Comment by SimonGer** [comment]
The input is (x, y, score), so 2D keypoints plus confidence value.

**Comment by Arginonn** [comment]
> The input is (x, y, score), so 2D keypoints plus confidence value.

I understand, thank you very much for your answer!
