### ISSUE TITLE
Input normalization

### ISSUE THREAD

**Issue by SimonGer** [TaatiTeam/MotionAGFormer#51]
Hi, thanks for your great work! It is very easy to work with!

I‘m working on using the model for inference and I‘m wondering why was the decision made to normalize with regards to the image dimensions? Wouldn‘t normalizing in reference to the pose make more sense? So for example pelvis is 0,0 and the sequence absolute max determines the scale?
As it is, the performance starts to degrade with very small keypoints.
What do you think should be best practice for normalizing input keypoints in the wild?

Thanks a lot!

**Comment by SoroushMehraban** [comment]
Hi @SimonGer,
Honestly I haven't investigated the effect of different normalizations. I used the same thing that MotionBERT used. You're free to try and see which one works the best 🙂
