### ISSUE TITLE
Visual comparison

### ISSUE THREAD

**Issue by l2day** [TaatiTeam/MotionAGFormer#52]
Hello, I would like to ask how the paper visualizes the comparison between inference results and truth results.Looking forward to your reply.

**Comment by SoroushMehraban** [comment]
@l2day  It's something like the visualization [here](https://github.com/TaatiTeam/MotionAGFormer/blob/master/data/preprocess/visualize.py#L82) with the difference that we visualize two sequences in different colors.

**Comment by l2day** [comment]
Thank you for your reply. In the visualization comparison with other papers, may I ask if the input data is the same as the data used in this model (H36M-SH), as I noticed that the input data of other models is different from this model.

**Comment by l2day** [comment]
Hello, may I ask if you could share the code for this section? Because I always tilt the results when visualizing. Thank you for your reply.

**Comment by l2day** [comment]
Hello, may I ask if you could share the code for this section? Because I always find the results is tilted when visualizing. Thank you for your reply.
