### ISSUE TITLE
On evaluating the 3DHP dataset

### ISSUE THREAD

**Issue by LLLYLong** [TaatiTeam/MotionAGFormer#53]
Thanks to the author can bring such a great work. I would like to ask about the metrics of the dataset 3DHP, i.e. PCK and AUC, how to set them up, I looked at the source dataset but the writeup is not very clear, can the authors explain

**Comment by zdpyz** [comment]
@LLLYLong Use the training script to download the data set, put TS1-TS6 into the 3dhp_test folder, and use the mpii_test_predictions_py.m in the test_util folder to train myself to obtain the model. It should be a.mat file under the mpi-checkpoints folder

**Comment by SoroushMehraban** [comment]
@LLLYLong  On `train_3dhp.py` [at the end of the training](https://github.com/TaatiTeam/MotionAGFormer/blob/master/train_3dhp.py#L266) we call the `save_data_inference` function to store the data in a format that is expected for evaluation. Then we use [the original evaluation code written in matlab](https://github.com/paTRICK-swk/P-STMO/tree/main/3dhp_test) that expects the `.mat` file we saved and we run it for evaluation. Sorry for this short response I did the project a year ago and I don't remember in more details.

**Comment by WY1433223** [comment]
你好，我想问一下，就是使用作者推荐的mpi的输入，我将其放在指定文件夹训练，可是怎么训练了一轮误差那么大？

<img width="388" height="130" alt="Image" src="https://github.com/user-attachments/assets/294c0c4e-a7ef-4629-9802-b69340b1df93" />
