### ISSUE TITLE
Questions about the evaluation strategy

### ISSUE THREAD

**Issue by l2day** [TaatiTeam/MotionAGFormer#54]
Hi，
I have a question about the parameters "2.5d_factor" and "joint_2.5d_image" in the test set. Why don't the output of the model be evaluated directly with the "joint3d_images" calculation MPJPE?
Thanks in advance.

**Comment by SoroushMehraban** [comment]
@l2day 
I explained here (https://github.com/TaatiTeam/MotionAGFormer/issues/4#issuecomment-1847441992) why.
