### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by l2day** [TaatiTeam/MotionAGFormer#55]
Hello, may I ask if there is an error in this line of code? https://github.com/TaatiTeam/MotionAGFormer/blob/4756fd1eb7cc73f0e991f091ff2280e030ab85f3/model/MotionAGFormer.py#L145
Should it be changed 
”x_graph = self.graph_temporal(self.graph_spatial(x_graph))“？

**Comment by SoroushMehraban** [comment]
@l2day  The line of code you're referring to is for the case when hierarchical mode is set to be True. That was one of the ablations we did (not mentioned in paper) and it's set to `False` by default. So the execution should never reach that line of code.
