### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by l2day** [TaatiTeam/MotionAGFormer#56]
Hello, in comparison with other papers on visualization, is this paper setting the Human3.6M dataset in the same way as Video Pose 3D or MotionBETR? Thank you for your reply.

**Comment by SoroushMehraban** [comment]
@l2day  If I remember correctly for a fair comparison in visual comparison, we used data preprocessing unique per model that we compared. MotionBERT and MotionAGFormer have the same data preprocessing but STCFormer and PoseFormerV2 were different.

**Comment by l2day** [comment]
> @l2day 如果我没记错的话，为了在视觉比较中进行公平比较，我们使用了每个比较模型独有的数据预处理。MotionBERT 和 MotionAGFormer 具有相同的数据预处理，但 STCFormer 和 PoseFormerV2 不同。

Can you provide the specific code? It would be very helpful to me. Thank you very much for your reply.

**Comment by SoroushMehraban** [comment]
@l2day Sorry I don't have access to that code anymore.
