### ISSUE TITLE
PCK&AUC

### ISSUE THREAD

**Issue by AsukaCamellia** [TaatiTeam/MotionAGFormer#6]
Hi！Thank you for the excellent project and I am very interested in your project. How can I measure PCK AUC on the MPI dataset？

**Comment by SoroushMehraban** [comment]
Hello @AsukaCamellia,
We have defined a function called `save_data_inference` [here](https://github.com/TaatiTeam/MotionAGFormer/blob/master/train_3dhp.py#L169C20-L169C20) that stores a matlab file called `inference_data.mat` and `'inference_data_best.mat`. The evaluation code for PCK and AUC is written in matlab and can be seen in repositories like [STCFormer](https://github.com/zhenhuat/STCFormer/tree/main/3dhp_test). I used `mpii_test_predictions_py.m` if I remember correctly. Note that the matlab code also requires some ground truth annotations which they can be downloaded from [the official website of MPI-INF-3DHP](https://vcai.mpi-inf.mpg.de/3dhp-dataset/). For downloading them you have to first download the small zip file and inside it there should be a bash file which you can run to download the annotations. Do not forget to adjust the config inside the zip file first.

**Comment by AsukaCamellia** [comment]
> Hello @AsukaCamellia, We have defined a function called `save_data_inference` [here](https://github.com/TaatiTeam/MotionAGFormer/blob/master/train_3dhp.py#L169C20-L169C20) that stores a matlab file called `inference_data.mat` and `'inference_data_best.mat`. The evaluation code for PCK and AUC is written in matlab and can be seen in repositories like [STCFormer](https://github.com/zhenhuat/STCFormer/tree/main/3dhp_test). I used `mpii_test_predictions_py.m` if I remember correctly. Note that the matlab code also requires some ground truth annotations which they can be downloaded from [the official website of MPI-INF-3DHP](https://vcai.mpi-inf.mpg.de/3dhp-dataset/). For downloading them you have to first download the small zip file and inside it there should be a bash file which you can run to download the annotations. Do not forget to adjust the config inside the zip file first.

Thank you for your answer!!!!
