### ISSUE TITLE
How to output the 3D pose estimation of an image？

### ISSUE THREAD

**Issue by Nancy-sn** [TaatiTeam/MotionAGFormer#60]
I'd like to ask everyone how to output the 3D pose estimation of an image.

**Comment by SoroushMehraban** [comment]
@Nancy-sn MotionAGFormer is a video-based method. You have to extract 2D poses from frames using an off-the-shelf pose detector (same as one used in demo) and then use them as input for 2D-3D lifting. For image alone you have to rely on other image-based methods.
