### ISSUE TITLE
result of 2d ground truth

### ISSUE THREAD

**Issue by l2day** [TaatiTeam/MotionAGFormer#63]
Hello, when using 2d ground truth training, I set use_daj_as_2d to True, but my results are higher than those in the paper. I would like to ask about the specific parameter settings for the 2d ground truth results in the paper

**Comment by SoroushMehraban** [comment]
@l2day How much difference are you observing? Note that selection of GPU and batch size also matters. We have used 2x A40 GPUs so when you see batch size is 16 in config, that means each GPU has received batch of 8 data. So Maybe you'll get a closer result compared to paper if you divide the batch size by 2 in case you are using one gpu or multiply by 2 if you use 4 GPUs. The choice of GPU also matters and it is hard to replicate the exact same result when using a different GPU.
