### ISSUE TITLE
2D GT for Human3.6M

### ISSUE THREAD

**Issue by Crazy-wu-20** [TaatiTeam/MotionAGFormer#7]
Excuse me, how can I get and preprocess the 2D Groud Truth data for Human3.6M? Could you share the code? Thank you very much!
I appreciate for your great work!
My email: bulrushwl@outlook.com

**Comment by Crazy-wu-20** [comment]
Oh I've sawn the answer, thx.

**Comment by liuxing007** [comment]
Excuse me, we also need guidance on how to  get and preprocess the 2D Groud Truth data for Human3.6M. Could you share the code? Thank you very much!
I appreciate for your great work!
My email: liuxing@sz.pku.edu.cn

**Comment by junbao-q** [comment]
Excuse me, we also need guidance on how to get and preprocess the 2D Groud Truth data for Human3.6M. Could you share the code? Thank you very much!
we also wish to express our sincere appreciation for your outstanding work!
My email: lijun.wang@stu.cqu.edu.cn
